### ISSUE TITLE
"update" in ILIAS causes error

### ISSUE THREAD

**Issue by tmuellerdatabay** [studer-raimann/PegasusHelper#1]
My Installation stuck on "update" the plugin.

Latest ILIAS 5.3.4 (latest git commit)

root@ilias:/srv/www/ilias-test.domain.de/log/ilias_errors# cat mt12q_9924.log
Whoops\Exception\ErrorException thrown with message "Invalid argument supplied for foreach()"

Stacktrace:
#15 Whoops\Exception\ErrorException in /srv/www/ilias-test.domain.de/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/PegasusHelper/classes/handler/OAuthManager/v52/OauthManagerImpl.php:138
#14 ilErrorHandling:handlePreWhoops in /srv/www/ilias-test.domain.de/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/PegasusHelper/classes/handler/OAuthManager/v52/OauthManagerImpl.php:138
#13 SRAG\PegasusHelper\handler\OAuthManager\v52\OauthManagerImpl:getRestClientId in /srv/www/ilias-test.domain.de/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/PegasusHelper/classes/rest/RestSetup.php:86
#12 SRAG\PegasusHelper\rest\RestSetup:addRoute in /srv/www/ilias-test.domain.de/ilias/Services/Database/classes/class.ilDBUpdate.php:457
#11 eval in /srv/www/ilias-test.domain.de/ilias/Services/Database/classes/class.ilDBUpdate.php:457
#10 ilDBUpdate:applyUpdateNr in /srv/www/ilias-test.domain.de/ilias/Services/Database/classes/class.ilDBUpdate.php:314
#9 ilDBUpdate:applyUpdate in /srv/www/ilias-test.domain.de/ilias/Services/Component/classes/class.ilPlugin.php:482
#8 ilPlugin:updateDatabase in /srv/www/ilias-test.domain.de/ilias/Services/Component/classes/class.ilPlugin.php:938
#7 ilPlugin:update in /srv/www/ilias-test.domain.de/ilias/Services/Component/classes/class.ilObjComponentSettingsGUI.php:516
#6 ilObjComponentSettingsGUI:update in /srv/www/ilias-test.domain.de/ilias/Services/Component/classes/class.ilObjComponentSettingsGUI.php:505
#5 ilObjComponentSettingsGUI:updatePlugin in /srv/www/ilias-test.domain.de/ilias/Services/Component/classes/class.ilObjComponentSettingsGUI.php:90
#4 ilObjComponentSettingsGUI:executeCommand in /srv/www/ilias-test.domain.de/ilias/Services/UICore/classes/class.ilCtrl.php:197
#3 ilCtrl:forwardCommand in /srv/www/ilias-test.domain.de/ilias/Services/Administration/classes/class.ilAdministrationGUI.php:284
#2 ilAdministrationGUI:executeCommand in /srv/www/ilias-test.domain.de/ilias/Services/UICore/classes/class.ilCtrl.php:197
#1 ilCtrl:forwardCommand in /srv/www/ilias-test.domain.de/ilias/Services/UICore/classes/class.ilCtrl.php:159
#0 ilCtrl:callBaseClass in /srv/www/ilias-test.domain.de/ilias/ilias.php:21

-- GET Data --

ref_id                   : 31
admin_mode               : settings
ctype                    : Services
cname                    : UIComponent
slot_id                  : uihk
pname                    : PegasusHelper
cmd                      : updatePlugin
cmdClass                 : ilobjcomponentsettingsgui
cmdNode                  : 12:iv
baseClass                : ilAdministrationGUI
lang                     : de
limit                    : 10

-- POST Data --

empty

-- Files --

empty

-- Cookies --

ilClientId               : ClientTest
PHPSESSID                : mt12qpve23ge0a91b14as3o2b1
il_sr_kathoAdminTest_status: unlocked

-- Session --

tbl_limit                : 10
post_vars                : Array
                         (
                         )

referer_ref_id           : 31
_authsession_expired     : 0
SessionType              : 2
_authsession_authenticated: 1
_authsession_user_id     : 31934
orig_request_target      :
has_to_accept_agr_in_session: 1
lang                     : de
il_pd_history            : ilcolumngui
awrn_last_update         : 1525682058
awrn_nr_users            : 0
awrn_nr_husers           : 0
table                    : Array
                         (
                             [cmpspl] => Array
                                 (
                                     [31934] => Array
                                         (
                                             [offset] => 0
                                         )

                                 )

                         )

il_rep_mode              : tree
il_rep_ref_id            : 1
referer                  : /ilias.php?ref_id=31&admin_mode=settings&cmd=view&cmdClass=ilobjcomponentsettingsgui&cmdNode=12:iv&baseClass=ilAdministrationGUI

**Comment by Idrimi** [comment]
I think this Issue can be closed. Thx @tmuellerdatabay for reporting.
